/**
 * ParkiPay — Billing routes
 *
 * POST /api/billing/generate/        — Global duplicate check + generate CN
 * GET  /api/billing/history/         — Officer's bill history for today
 * GET  /api/billing/:cn/status/      — Bill status by control number
 */
const { Router }       = require('express');
const { z }            = require('zod');
const prisma           = require('../lib/prisma');
const logAction        = require('../lib/audit');
const { authenticate } = require('../middleware/auth');
const cfg              = require('../config');
const {
  generateControlNumber,
  getActiveBillForPlate,
} = require('../lib/controlNumber');

const router = Router();

// All billing routes require authentication
router.use(authenticate);

// ── POST /api/billing/generate/ ───────────────────────────────────────────────

const GenerateSchema = z.object({
  plate_number: z.string().min(1, 'plate_number is required'),
  location_id:  z.number().int().positive('location_id must be a positive integer'),
});

router.post('/generate/', async (req, res, next) => {
  try {
    const parsed = GenerateSchema.safeParse(req.body);
    if (!parsed.success) {
      return res.status(400).json({
        error:  'validation_error',
        detail: parsed.error.flatten(),
      });
    }

    const { plate_number, location_id } = parsed.data;
    const plate = plate_number.trim().toUpperCase().replace(/\s/g, '');

    // ── 1. Global duplicate check (core engine) ────────────────────────────
    const existing = await getActiveBillForPlate(plate);
    if (existing) {
      await logAction(req.officer, logAction.ACTIONS.BILL_DUPLICATE_BLOCKED, {
        plateNumber:   plate,
        controlNumber: existing.controlNumber,
        result:        'duplicate_blocked',
        req,
      });
      return res.status(409).json({
        error:  'duplicate_bill',
        detail: 'This vehicle already has an active parking bill.',
        existing_bill: {
          control_number: existing.controlNumber,
          expires_at:     existing.expiresAt,
          issued_by:      existing.officer?.fullName ?? null,
          location:       existing.location?.name   ?? null,
        },
      });
    }

    // ── 2. Validate parking location ──────────────────────────────────────
    const location = await prisma.parkingLocation.findUnique({
      where: { id: location_id },
    });
    if (!location || !location.isActive) {
      return res.status(400).json({
        error:  'invalid_location',
        detail: 'Parking location not found or inactive.',
      });
    }

    // ── 3. Optional vehicle registry lookup (bill can proceed without it) ─
    const vehicle = await prisma.vehicle.findUnique({
      where: { plateNumber: plate },
    });

    // ── 4. Determine fee by vehicle category ──────────────────────────────
    const feeMap = {
      MOTORCYCLE:  location.feeMotorcycle,
      PRIVATE_CAR: location.feePrivateCar,
      MINIBUS:     location.feeMinibus,
      BUS:         location.feeBus,
      TRUCK:       location.feeTruck,
      GOVERNMENT:  location.feeGovernment,
    };
    const amountDue = feeMap[vehicle?.category ?? 'PRIVATE_CAR'] ?? location.feePrivateCar;

    // ── 5. Create the bill ─────────────────────────────────────────────────
    const expiresAt = new Date(Date.now() + cfg.billing.validityHours * 3_600_000);
    const bill = await prisma.controlNumber.create({
      data: {
        controlNumber: generateControlNumber(),
        plateNumber:   plate,
        vehicleId:     vehicle?.id ?? null,
        officerId:     req.officer.id,
        locationId:    location.id,
        amountDue,
        expiresAt,
      },
      include: { officer: true, location: true, vehicle: true },
    });

    await logAction(req.officer, logAction.ACTIONS.BILL_GENERATED, {
      plateNumber:   plate,
      controlNumber: bill.controlNumber,
      result:        'success',
      req,
    });

    return res.status(201).json(bill);
  } catch (err) {
    next(err);
  }
});

// ── GET /api/billing/history/ ─────────────────────────────────────────────────

router.get('/history/', async (req, res, next) => {
  try {
    // Return bills generated by this officer since midnight today
    const startOfDay = new Date();
    startOfDay.setHours(0, 0, 0, 0);

    const bills = await prisma.controlNumber.findMany({
      where: {
        officerId:   req.officer.id,
        generatedAt: { gte: startOfDay },
      },
      include:  { location: true, vehicle: true },
      orderBy:  { generatedAt: 'desc' },
    });

    return res.json(bills);
  } catch (err) {
    next(err);
  }
});

// ── GET /api/billing/:cn/status/ ──────────────────────────────────────────────

router.get('/:cn/status/', async (req, res, next) => {
  try {
    const bill = await prisma.controlNumber.findUnique({
      where:   { controlNumber: req.params.cn },
      include: { officer: true, location: true },
    });

    if (!bill) {
      return res.status(404).json({
        error:  'not_found',
        detail: 'Control number not found.',
      });
    }

    const minutesRemaining = Math.max(
      0,
      Math.floor((new Date(bill.expiresAt) - Date.now()) / 60_000),
    );

    return res.json({ ...bill, minutesRemaining });
  } catch (err) {
    next(err);
  }
});

module.exports = router;
