# Generated by Django 6.0.5 on 2026-05-15 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(
                    max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False,
                 help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('employee_id', models.CharField(db_index=True,
                 help_text='Government-issued employee ID. Used for login.', max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('FIELD_OFFICER', 'Field Officer'), (
                    'SUPERVISOR', 'Supervisor'), ('ADMIN', 'Administrator')], default='FIELD_OFFICER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                 related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='officers', to='vehicles.parkinglocation')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.',
                 related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Officer',
                'verbose_name_plural': 'Officers',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILURE', 'Login Failure'), ('LOGIN_LOCKED', 'Login Attempt — Account Locked'), ('LOGOUT', 'Logout'), ('TOKEN_REFRESH', 'Token Refresh'), (
                    'BILL_GENERATED', 'Bill Generated'), ('BILL_DUPLICATE_BLOCKED', 'Duplicate Bill Blocked'), ('VEHICLE_LOOKUP', 'Vehicle Lookup'), ('PLATE_NOT_FOUND', 'Plate Not Found')], db_index=True, max_length=40)),
                ('plate_number', models.CharField(
                    blank=True, db_index=True, max_length=20)),
                ('control_number', models.CharField(blank=True, max_length=30)),
                ('result', models.CharField(blank=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(
                    auto_now_add=True, db_index=True)),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['officer', 'timestamp'], name='accounts_au_officer_1fd0f6_idx'), models.Index(fields=['action', 'timestamp'], name='accounts_au_action_11cc52_idx')],
            },
        ),
    ]
